AWM: Extensive changes
Made many changes to the autostart file. Also made some smaller changes
to rc.lua and theme/theme.lua.

diff --git a/awesome/autostart b/awesome/autostart
--- a/awesome/autostart
+++ b/awesome/autostart
@@ -1,51 +1,48 @@
 #!/bin/sh
 
-## Openbox autostart.sh
-## ====================
-## When you login to your CrunchBang Openbox session, this autostart script 
-## will be executed to set-up your environment and launch any applications
-## you want to run at startup.
-##
-## Note*: some programs, such as 'nm-applet' are run via XDG autostart.
-## Run '/usr/lib/openbox/openbox-xdg-autostart --list' to list any
-## XDG autostarted programs.
-##
-## More information about this can be found at:
-## http://openbox.org/wiki/Help:Autostart
-##
-## If you do something cool with your autostart script and you think others
-## could benefit from your hack, please consider sharing it at:
-## http://crunchbang.org/forums/
-##
-## Have fun & happy CrunchBangin'! :)
+# @kludge: make it possible to restart awesome without running this script twice
+if [ -f '/tmp/.awesomestart' ]; then
+  echo "Awesome has already been started. Aborting."
+  exit 1
+fi
+
+touch '/tmp/.awesomestart'
 
 ## Quad monitors
+# @todo: only run this on fourside
 xrandr --output DP-1    --mode 1920x1080 --pos 1080x0    --rotate inverted \
        --output DVI-I-1 --mode 1920x1080 --pos 0x1080    --rotate left \
        --output DVI-D-1 --mode 1920x1080 --pos 3000x1080 --rotate right \
        --output HDMI-1  --mode 1920x1080 --pos 1080x1080 --rotate normal
 
+
 ## GNOME PolicyKit and Keyring
 eval $(gnome-keyring-daemon -s --components=pkcs11,secrets,ssh,gpg) &
 
 ## Set root window colour
-hsetroot -solid "#2E3436"
+hsetroot -solid "#2E3436" &
 
-## Background and compositor
-nitrogen --restore
-cb-compositor --start
+## Wallpaper and compositor
+(\
+nitrogen --restore && \
+cb-compositor --start && \
+sleep 5s
+) &
 
 ## Volume keys daemon
-xfce4-volumed
+xfce4-volumed &
 
 ## Enable power management
-xfce4-power-manager
+xfce4-power-manager &
+
+## Mixer
+pavucontrol &
 
 ## Detect and configure touchpad. See 'man synclient' for more info.
-if egrep -iq 'touchpad' /proc/bus/input/devices; then
-    synclient VertEdgeScroll=1 &
-    synclient TapButton1=1 &
-fi
+#if egrep -iq 'touchpad' /proc/bus/input/devices; then
+    #synclient VertEdgeScroll=1 &
+    #synclient TapButton1=1 &
+#fi
 
 ## Start xscreensaver
 xscreensaver -no-splash &
@@ -54,13 +51,13 @@ xscreensaver -no-splash &
 #(sleep 3s && clipit) &
 
 ## Adjust the values according to your preferences.
-xset r rate 150 50
+xset r rate 250 30 &
 
 ## Turn on/off system beep
-xset b off
+xset b off &
 
 ## Run the conky
-conky -q &
+#conky -q &
 
 ## Synapse
 synapse --startup
